### ISSUE TITLE
Attribute error when creating environment from yml

### ISSUE THREAD

**Issue by natalieadye** [CSBDeep/CSBDeep#68]
Hello, 

I'm hoping you can help me with an installation issue. Last year, I installed the environment from https://raw.githubusercontent.com/CSBDeep/CSBDeep/master/extras/environment-gpu-py3.8-tf2.4.yml and it worked. When I try again now to reinstall it afresh on the same computer, it get "Attribute Error: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'. We tried it on different user accounts or the same, and it always fails. I am working on a Linux, Ubuntu 20.04.5LTS with NVIDIA GeForce 3090 RTX GPU. 

Do you have any recommendations? 
Thanks, Natalie

![csbdeeperror](https://user-images.githubusercontent.com/125257076/218666564-8c8b18c9-9c10-4a23-9641-99902937f569.png)

**Comment by maweigert** [comment]
Hm, seems to be python/pip related issue. Might be related to [this](https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss) ?
